
vnpay.tmn_code=JOIW5CDF
vnpay.hash_secret=VI4HEZXFZ8SMH6JC35KYVW4VKP0Q9WIG
vnpay.pay_url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return_url=http://localhost:8080/ShopQuanAo_war/vnpay-return
vnpay.version=2.1.0
vnpay.command=pay
vnpay.order_type=other
